import Challenge.Specs.ShortWeierstrass
import Mathlib.Algebra.Field.ZMod
import Mathlib.Data.Nat.Digits.Defs
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

namespace Specs.Bls12381G1

open Specs.ShortWeierstrass

/-!
Trusted spec for scalar multiplication on the BLS12-381 G1 curve.

BLS12-381 G1 is the short Weierstrass curve `y² = x³ + 4` over the 381-bit
prime field `𝔽_p`. The group `E(𝔽_p)` has order `h₁ · r` with **cofactor
`h₁ ≠ 1`**, so unlike secp256k1 the group order is composite and the curve
admits points outside the order-`r` subgroup. Scalar multiplication is only
required to behave on the prime-order subgroup: the variable-base challenge
assumes its base point lies in the subgroup generated by `G`, and every spec
below additionally requires the result to lie in that subgroup.
-/

/-- The prime `p` of the BLS12-381 base field (IETF/Zcash `BLS12-381`), a
381-bit prime derived from `z = -0xd201000000010000` via
`p = (z-1)²(z⁴-z²+1)/3 + z`. -/
def p : ℕ :=
  0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab

/-- `p` is prime (axiom; a challenge instance must whitelist it in its
comparator config). -/
axiom hPrime : p.Prime

instance : Fact p.Prime := ⟨hPrime⟩

/-- The BLS12-381 base field `𝔽_p`. -/
abbrev Fp : Type := ZMod p

/-- BLS12-381 G1: `y² = x³ + 4`. -/
def curve : Curve Fp := { a := 0, b := 4 }

/-- The BLS12-381 G1 curve equation, with the concrete coefficients inlined. -/
lemma onCurve_iff (P : Point Fp) :
    OnCurve curve P ↔ P.y ^ 2 = P.x ^ 3 + 4 := by
  simp [OnCurve, curve]

/-- `2 ≠ 0` in the BLS12-381 base field. -/
lemma two_ne_zero_fp : (2 : Fp) ≠ 0 := by
  have h2 : ((2 : ℕ) : Fp) ≠ 0 := by
    rw [Ne, ZMod.natCast_eq_zero_iff]
    intro hdvd
    have hle : p ≤ 2 := Nat.le_of_dvd (by norm_num) hdvd
    have hp : 2 < p := by norm_num [p]
    exact (Nat.not_lt_of_ge hle) hp
  simpa using h2

/-- `3 ≠ 0` in the BLS12-381 base field. -/
lemma three_ne_zero_fp : (3 : Fp) ≠ 0 := by
  have h3 : ((3 : ℕ) : Fp) ≠ 0 := by
    rw [Ne, ZMod.natCast_eq_zero_iff]
    intro hdvd
    have hle : p ≤ 3 := Nat.le_of_dvd (by norm_num) hdvd
    norm_num [p] at hle
  simpa using h3

/-- `4 ≠ 0` in the BLS12-381 base field. -/
lemma four_ne_zero_fp : (4 : Fp) ≠ 0 := by
  have h4 : ((4 : ℕ) : Fp) ≠ 0 := by
    rw [Ne, ZMod.natCast_eq_zero_iff]
    intro hdvd
    have hle : p ≤ 4 := Nat.le_of_dvd (by norm_num) hdvd
    norm_num [p] at hle
  simpa using h4

/-- The BLS12-381 chord formula lands back on the curve. -/
theorem chord_onCurve {P Q : Point Fp} (hP : OnCurve curve P)
    (hQ : OnCurve curve Q) (hx : P.x ≠ Q.x) :
    OnCurve curve (chord P Q) := by
  rcases P with ⟨px, py⟩
  rcases Q with ⟨qx, qy⟩
  rw [onCurve_iff] at hP hQ ⊢
  dsimp [chord]
  have hne : qx - px ≠ 0 := sub_ne_zero.mpr hx.symm
  exact chord_onCurve_cubic hP hQ hne (by rw [div_mul_cancel₀ _ hne]) rfl rfl

/-- The BLS12-381 tangent formula lands back on the curve when the tangent
denominator is nonzero. -/
theorem tangent_onCurve {P : Point Fp} (hP : OnCurve curve P) (hy : P.y ≠ 0) :
    OnCurve curve (tangent curve P) := by
  rcases P with ⟨px, py⟩
  rw [onCurve_iff] at hP ⊢
  have hden : (2 : Fp) * py ≠ 0 := mul_ne_zero two_ne_zero_fp hy
  dsimp [tangent, curve]
  exact tangent_onCurve_cubic hP (by rw [div_mul_cancel₀ _ hden]; simp) (by ring) rfl

/-- Complete BLS12-381 G1 point addition preserves curve membership, provided
the curve has no affine order-two points. (`E(𝔽_p)` in fact has odd order
`h₁·r`, so the hypothesis always holds here.) -/
theorem add_onCurve_or_infinity
    (hNoOrderTwo : NoOrderTwo curve)
    {P Q : GroupPoint Fp}
    (hP : OnCurveOrInfinity curve P) (hQ : OnCurveOrInfinity curve Q) :
    OnCurveOrInfinity curve (add curve P Q) := by
  cases P with
  | infinity =>
      simpa [OnCurveOrInfinity, add] using hQ
  | affine P =>
      cases Q with
      | infinity =>
          simpa [OnCurveOrInfinity, add] using hP
      | affine Q =>
          dsimp [OnCurveOrInfinity] at hP hQ
          change OnCurveOrInfinity curve
            (if P.x = Q.x then
              if P.y = -Q.y then .infinity else .affine (tangent curve P)
            else .affine (chord P Q))
          split
          · split
            · trivial
            · exact tangent_onCurve hP (hNoOrderTwo P hP)
          · exact chord_onCurve hP hQ ‹P.x ≠ Q.x›

/-- The standard generator `G` of the prime-order subgroup (the IETF/Zcash
BLS12-381 G1 generator). -/
def G : Point Fp := {
  x := 0x17f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb
  y := 0x8b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1
}

/-- The prime order `r = z⁴ - z² + 1` (with `z = -0xd201000000010000`) of the
subgroup generated by `G` — the BLS12-381 scalar field. -/
def order : ℕ :=
  0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001

/-- The cofactor `h₁ = (z-1)²/3` of the G1 group: `E(𝔽_p)` has order
`h₁ · r` (about 2¹²⁶ · r). Because `h₁ ≠ 1`, the group order is not prime
and `E(𝔽_p)` has points outside the subgroup generated by `G`. -/
def cofactor : ℕ :=
  0x396c8c005555e1568c00aaab0000aaab

/-- The `n`-fold sum `[n]Q`, used to state subgroup membership. Delegates to
the curve-generic double-and-add `curveNsmul` (O(log n) group operations), so
subgroup facts are decidable by `native_decide` — a unary successor recursion
would recurse 2²⁵⁵ times at `n = order`. -/
def nsmul (n : ℕ) (Q : GroupPoint Fp) : GroupPoint Fp :=
  curveNsmul curve n Q

/-- Membership in the prime-order subgroup (the identity included): the
points killed by `[r]·`. Since `gcd(h₁, r) = 1`, the `r`-torsion of
`E(𝔽_p)` is exactly the order-`r` subgroup generated by `G`, so this is
the standard subgroup-membership check. -/
@[reducible] def InSubgroup (Q : GroupPoint Fp) : Prop :=
  nsmul order Q = .infinity

/-- The prime-order subgroup is closed under scalar multiplication: if `Q`
is killed by `[r]·` then so is `[k]Q`. This is the fact a solution uses to
discharge the spec's subgroup-membership obligation for its output (whose
on-curve-ness is immediate from the circuit's soundness), and — unlike
cofactor clearing — it needs no group-order input: it follows from the
proven scalar-multiplication homomorphism lemmas alone. -/
theorem inSubgroup_nsmul {k : ℕ} {Q : GroupPoint Fp}
    (hQo : OnCurveOrInfinity (cubicCurve 4) Q) (hQ : InSubgroup Q) :
    InSubgroup (nsmul k Q) := by
  have hQ' : curveNsmul (cubicCurve 4) order Q = .infinity := hQ
  show curveNsmul (cubicCurve 4) order (curveNsmul (cubicCurve 4) k Q) = GroupPoint.infinity
  rw [← curveNsmul_mul two_ne_zero_fp three_ne_zero_fp four_ne_zero_fp (m := order)
      (k := k) Q hQo, Nat.mul_comm,
    curveNsmul_mul two_ne_zero_fp three_ne_zero_fp four_ne_zero_fp (m := k) (k := order)
      Q hQo, hQ']
  rfl

/-- Scalar multiplication on subgroup points only depends on the scalar mod
`r`: `[k]Q = [k mod r]Q`. Together with `inSubgroup_nsmul` and the
proven additivity/multiplicativity of `curveNsmul`, this lets a solution
freely decompose the scalar — GLV-style `k ≡ k₁ + k₂·c` splits, windowed
and fixed-base methods — and relate the pieces back to the spec's
unreduced 255-bit scalar. -/
theorem nsmul_mod_order (k : ℕ) {Q : GroupPoint Fp}
    (hQo : OnCurveOrInfinity (cubicCurve 4) Q) (hQ : InSubgroup Q) :
    nsmul (k % order) Q = nsmul k Q := by
  have hQ' : curveNsmul (cubicCurve 4) order Q = .infinity := hQ
  show curveNsmul (cubicCurve 4) (k % order) Q
    = curveNsmul (cubicCurve 4) k Q
  conv_rhs => rw [← Nat.div_add_mod k order]
  rw [curveNsmul_add two_ne_zero_fp three_ne_zero_fp four_ne_zero_fp
      (u := order * (k / order)) (v := k % order) Q hQo]
  rw [Nat.mul_comm, curveNsmul_mul two_ne_zero_fp three_ne_zero_fp four_ne_zero_fp
      (m := k / order) (k := order) Q hQo, hQ']
  rfl

/-- The digit fold of `scalarMul` agrees with `curveNsmul`: the MSB-first
double-and-add over the bits computes `[scalarOfBits bits]P`. This is the
bridge a solution uses to turn the spec's bit-fold statement
(`Specs.ShortWeierstrass.Spec`) into `nsmul` facts such as subgroup
membership (`inSubgroup_nsmul`). -/
theorem scalarMul_eq_nsmul {n : ℕ} (bits : Vector ℕ n) (hb : IsBitArray bits)
    (P : Point Fp) :
    Specs.ShortWeierstrass.scalarMul curve bits P
      = nsmul (Specs.ShortWeierstrass.scalarOfBits bits) (.affine P) := by
  -- digit-map left fold: `2*acc + b` shifts in `b` at weight `2^l.length`
  have hvalue : ∀ (l : List ℕ) (x : ℕ),
      l.foldl (fun acc b => 2 * acc + b) x
        = x * 2 ^ l.length + l.foldl (fun acc b => 2 * acc + b) 0 := by
    intro l
    induction l with
    | nil => intro x; simp
    | cons b l ih =>
        intro x
        rw [List.foldl_cons, ih (2 * x + b)]
        rw [List.foldl_cons, ih (2 * 0 + b)]
        simp only [Nat.mul_zero, Nat.zero_add, List.length_cons, Nat.pow_succ]
        ring
  -- the double-and-add invariant, generalized over the running accumulator
  have key : ∀ (l : List ℕ) (v : ℕ), (∀ b ∈ l, b < 2) →
      l.foldl (Specs.ShortWeierstrass.step curve P)
          (curveNsmul curve v (.affine P))
        = curveNsmul curve (v * 2 ^ l.length + l.foldl (fun acc b => 2 * acc + b) 0)
            (.affine P) := by
    intro l
    induction l with
    | nil => intro v _; simp
    | cons b l ih =>
        intro v hbl
        have hb2 : b < 2 := hbl b (List.mem_cons_self ..)
        have hbl' : ∀ b' ∈ l, b' < 2 := fun b' hb' => hbl b' (List.mem_cons_of_mem _ hb')
        -- one step doubles and conditionally adds
        have hstepval :
            Specs.ShortWeierstrass.step curve P (curveNsmul curve v (.affine P)) b
              = curveNsmul curve (2 * v + b) (.affine P) := by
          rcases Nat.eq_zero_or_pos b with h0 | h0
          · subst h0
            simp only [Specs.ShortWeierstrass.step]
            rw [if_neg (by decide : ¬((0 : ℕ) = 1)), Nat.add_zero,
              curveNsmul_double]
          · have hb1 : b = 1 := by omega
            subst hb1
            simp only [Specs.ShortWeierstrass.step]
            rw [if_pos trivial, curveNsmul_succ, curveNsmul_double]
        rw [List.foldl_cons, hstepval, ih (2 * v + b) hbl']
        have hval : (b :: l).foldl (fun acc b => 2 * acc + b) 0
            = b * 2 ^ l.length + l.foldl (fun acc b => 2 * acc + b) 0 := by
          rw [List.foldl_cons, Nat.mul_zero, Nat.zero_add, hvalue l b]
        have harg : v * 2 ^ (b :: l).length
              + (b * 2 ^ l.length + l.foldl (fun acc b => 2 * acc + b) 0)
            = (2 * v + b) * 2 ^ l.length
              + l.foldl (fun acc b => 2 * acc + b) 0 := by
          simp only [List.length_cons, Nat.pow_succ]
          ring
        rw [hval, harg]
  -- the spec's `scalarMul` is the bit fold from `.infinity = [0]P`
  have h0 : curveNsmul curve 0 (.affine P) = .infinity := rfl
  have hvec : ∀ (v : Vector ℕ n) {α : Type} (g : α → ℕ → α) (init : α),
      v.foldl g init = v.toList.foldl g init := by
    intro v
    cases v
    simp [Vector.foldl, Array.foldl_toList]
  rw [Specs.ShortWeierstrass.scalarMul, hvec]
  rw [Specs.ShortWeierstrass.scalarOfBits, hvec, ← h0]
  rw [key bits.toList 0 (fun b hb' => by
    obtain ⟨i, hi, hbi⟩ := List.mem_iff_getElem.mp hb'
    have him : i < n := by simpa using hi
    have hbi' : bits[i] = b := by simpa using hbi
    rw [← hbi']
    exact hb ⟨i, him⟩), Nat.zero_mul, Nat.zero_add]
  rfl

/-- Scalars are presented as 255 bits, most significant bit first (the
bit length of `r`). -/
@[reducible] def scalarBits : ℕ := 255

end Specs.Bls12381G1


namespace Specs.Bls12381G1ScalarMul

open Specs.ShortWeierstrass Specs.Bls12381G1

/-- Input assumptions at spec level: the scalar entries are bits, the base
point lies on the curve, and — because the G1 group has a nontrivial
cofactor — the base point lies **in the prime-order subgroup**. Without
that assumption, `[k]P` would not even be determined by `[k mod r]`, and
the challenge's subgroup-guaranteed output would be ill-posed. -/
def Assumptions (bits : Vector ℕ scalarBits) (P : Point Fp) : Prop :=
  Specs.ShortWeierstrass.Assumptions curve bits P ∧
  InSubgroup (.affine P)

/-- The scalar multiplication relation: the output is the true multiple
`[scalarOfBits bits]P` (naive double-and-add with the complete group law)
**and lies in the prime-order subgroup**. For a base point in the subgroup
the membership conjunct is a mathematical consequence of the equation
(the subgroup is closed under the group law); it is stated explicitly so
every solution must witness it, as demanded by the cofactor setting. -/
def Spec (bits : Vector ℕ scalarBits) (P : Point Fp)
    (output : GroupPoint Fp) : Prop :=
  Specs.ShortWeierstrass.Spec curve bits P output ∧
  InSubgroup output

end Specs.Bls12381G1ScalarMul


namespace Specs.Bls12381G1ScalarMulFixedBase

open Specs.ShortWeierstrass Specs.Bls12381G1

/-- The fixed-base relation: the output is the true multiple of the fixed
generator `G` under the complete group law. Because the base point is the
**fixed** generator `G` — known (and tested, `Tests/Bls12381G1.lean`) to lie
in the prime-order subgroup — every output `[k]G` automatically lies in that
subgroup as well, so unlike the variable-base relation no
subgroup-membership conjunct is required of the circuit. -/
def Spec (bits : Vector ℕ scalarBits) (output : GroupPoint Fp) : Prop :=
  Specs.ShortWeierstrass.Spec curve bits G output

end Specs.Bls12381G1ScalarMulFixedBase
