import Mathlib.Data.Nat.Log

namespace Specs.Keccak

/-
  The Keccak-f permutation family, following "The Keccak Reference", Version 3.0
  (Bertoni, Daemen, Peeters, Van Assche, January 2011), Section 1.2, which is
  Keccak-p[b, 12 + 2ℓ] of FIPS 202, Section 3.

  Keccak-f[b] permutes a state of b = 25 · 2^ℓ bits, ℓ ∈ {0, ..., 6}, organized
  as a 5×5 array of w-bit lanes with w = 2^ℓ. A lane is represented as a natural
  number below 2^w; the lane at coordinates (x, y) is stored at index x + 5·y,
  so that state bit s[w·(5y + x) + z] is bit z of lane (x, y) (FIPS 202,
  Section 3.1.2). Each round applies the five steps θ, ρ, π, χ, ι in order.

  The main instance is Keccak-f[1600] (ℓ = 6, the SHA-3 permutation), exposed at
  the bottom of this file as `keccakF1600`, a permutation of 1600-bit strings.
-/

/-- Rotate the `w`-bit word `x` left by `offset` bits (`offset` is reduced mod `w`). -/
def rotLeft (w x offset : ℕ) : ℕ :=
  let r := offset % w
  (x * 2 ^ r + x / 2 ^ (w - r)) % 2 ^ w

/-- Bitwise complement of a `w`-bit lane. -/
def notLane (w a : ℕ) : ℕ := a ^^^ (2 ^ w - 1)

/-- Lane (x, y) of a state. -/
def lane (A : Vector ℕ 25) (x y : Fin 5) : ℕ := A[x.val + 5 * y.val]

/-- Build a state lane by lane. -/
def ofLanes (f : Fin 5 → Fin 5 → ℕ) : Vector ℕ 25 :=
  Vector.ofFn fun i => f ⟨i.val % 5, by omega⟩ ⟨i.val / 5, by omega⟩

-- θ: A[x,y] ← A[x,y] ⊕ D[x], where C[x] is the parity of column x and
--    D[x] = C[x−1] ⊕ ROT(C[x+1], 1) (coordinates mod 5)
def theta (w : ℕ) (A : Vector ℕ 25) : Vector ℕ 25 :=
  let C : Vector ℕ 5 := Vector.ofFn fun x =>
    lane A x 0 ^^^ lane A x 1 ^^^ lane A x 2 ^^^ lane A x 3 ^^^ lane A x 4
  let D : Vector ℕ 5 := Vector.ofFn fun x => C[x - 1] ^^^ rotLeft w C[x + 1] 1
  ofLanes fun x y => lane A x y ^^^ D[x]

/--
  The ρ rotation offsets, at index x + 5·y for lane (x, y): r[0,0] = 0 and
  r[x,y] = (t+1)(t+2)/2 where t walks (x, y) ← (y, 2x + 3y) starting from
  (1, 0). Offsets are stored unreduced and taken mod w when rotating.
-/
def rhoOffsets : Vector ℕ 25 := #v[
    0,   1, 190,  28,  91,
   36, 300,   6,  55, 276,
    3,  10, 171, 153, 231,
  105,  45,  15,  21, 136,
  210,  66, 253, 120,  78
]

-- ρ: A[x,y] ← ROT(A[x,y], r[x,y])
def rho (w : ℕ) (A : Vector ℕ 25) : Vector ℕ 25 :=
  Vector.ofFn fun i => rotLeft w A[i] rhoOffsets[i]

-- π: A[x,y] ← A[x + 3y, x] (equivalently, lane (x, y) moves to (y, 2x + 3y))
def pi (A : Vector ℕ 25) : Vector ℕ 25 :=
  ofLanes fun x y => lane A (x + 3 * y) x

-- χ: A[x,y] ← A[x,y] ⊕ (¬A[x+1,y] ∧ A[x+2,y]), the only non-linear step
def chi (w : ℕ) (A : Vector ℕ 25) : Vector ℕ 25 :=
  ofLanes fun x y => lane A x y ^^^ (notLane w (lane A (x + 1) y) &&& lane A (x + 2) y)

-- ι: A[0,0] ← A[0,0] ⊕ RC[i]
def iota (rc : ℕ) (A : Vector ℕ 25) : Vector ℕ 25 :=
  A.set 0 (A[0] ^^^ rc)

/--
  Round constants RC[i] for w = 64: bit 2^j − 1 of RC[i] is rc(j + 7i) for
  0 ≤ j ≤ 6, where rc(t) is the LFSR sequence generated by
  x⁸ + x⁶ + x⁵ + x⁴ + 1. For lane widths w < 64 the constants are the same
  values truncated mod 2^w.
-/
def roundConstants : Vector ℕ 24 := #v[
  0x0000000000000001, 0x0000000000008082, 0x800000000000808a, 0x8000000080008000,
  0x000000000000808b, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
  0x000000000000008a, 0x0000000000000088, 0x0000000080008009, 0x000000008000000a,
  0x000000008000808b, 0x800000000000008b, 0x8000000000008089, 0x8000000000008003,
  0x8000000000008002, 0x8000000000000080, 0x000000000000800a, 0x800000008000000a,
  0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008
]

-- One round of Keccak-f: R = ι ∘ χ ∘ π ∘ ρ ∘ θ
def keccakRound (w rc : ℕ) (A : Vector ℕ 25) : Vector ℕ 25 :=
  iota rc (chi w (pi (rho w (theta w A))))

/--
  The Keccak-f[25 · 2^ℓ] permutation on the 25 lanes of the state:
  12 + 2ℓ rounds with round constants RC[0], ..., RC[12 + 2ℓ − 1].
-/
def keccakF (l : Fin 7) (A : Vector ℕ 25) : Vector ℕ 25 :=
  let w := 2 ^ l.val
  Fin.foldl (12 + 2 * l.val)
    (fun A i => keccakRound w (roundConstants[i.val] % 2 ^ w) A) A

/-- Pack a 1600-bit string into 25 lanes: state bit 64·i + z is bit z of lane i. -/
def bitsToState (s : Vector ℕ 1600) : Vector ℕ 25 :=
  Vector.ofFn fun i =>
    Fin.foldl 64 (fun acc (z : Fin 64) => acc + s[64 * i.val + z.val] * 2 ^ z.val) 0

/-- Unpack 25 lanes into a 1600-bit string. -/
def stateToBits (A : Vector ℕ 25) : Vector ℕ 1600 :=
  Vector.ofFn fun i => A[i.val / 64] / 2 ^ (i.val % 64) % 2

/-- The Keccak-f[1600] permutation (ℓ = 6, the SHA-3 permutation) on 1600-bit strings. -/
def keccakF1600 (s : Vector ℕ 1600) : Vector ℕ 1600 :=
  stateToBits (keccakF 6 (bitsToState s))

/--
  A bit string represented as a vector of natural numbers.
-/
@[reducible] def IsBitString {n : ℕ} (xs : Vector ℕ n) : Prop :=
  ∀ i : Fin n, xs[i] < 2

def Assumptions (input : Vector ℕ 1600) : Prop :=
  -- input is a bit string
  IsBitString input

def Spec (input : Vector ℕ 1600) (output : Vector ℕ 1600) : Prop :=
  output = keccakF1600 input

end Specs.Keccak
