import Clean.Circuit
import Clean.Utils.Tactics.ProvableStructDeriving
import Challenge.Specs.Blake3
import Challenge.Utils.F2Bits

/-!
Bit-level semantics for the canonical BLAKE3 compression challenge over `F 2`.

The input uses the same raw 896-bit serialization as
`Specs.Blake3.compressBits`: 8 chaining-value words, 16 message words, the low
and high counter words, the block length, and the flags. The output is all 16
compression words (512 bits). Within every word, bit `32 * i + j` is bit `j`.

`Tests.Blake3` checks this independent GF(2) formulation against the
natural-number specification and vectors generated by the Rust `blake3` crate.
The interface module imports this file and contains only the challenge-facing
input, output, assumptions, and specification declarations.
-/

namespace Challenge.Instances.Blake3CompressGF2Canonical

namespace Interface

open Challenge.F2Bits

@[reducible] def inputBits : ℕ := 896
@[reducible] def outputBits : ℕ := 512

/-!
## Bit-level BLAKE3 compression over GF(2)

These definitions are the BLAKE3 compression function written directly on
little-endian 32-bit vectors. Addition is the ordinary ripple-carry full adder;
XOR is field addition; rotations only re-index bits. Keeping this semantics in
the trusted interface makes the challenge's bit relation independent of the
reference circuit below.
-/

namespace Blake3Bits

abbrev Word (α : Type) := Vector α 32
abbrev State (α : Type) := Vector α 512
abbrev Block (α : Type) := Vector (Word α) 16

structure Quad (α : Type) where
  a : Word α
  b : Word α
  c : Word α
  d : Word α
deriving ProvableStruct

@[reducible] def atWord {α : Type} (v : Word α) (i : ℕ) : α :=
  v[i % 32]'(Nat.mod_lt _ (by norm_num))

def splitWords {α : Type} (n : ℕ) (v : Vector α (32 * n)) : Vector (Word α) n :=
  Vector.ofFn fun i => Vector.ofFn fun j =>
    v[32 * i.val + j.val]'(by omega)

def flattenWords {α : Type} {n : ℕ} (v : Vector (Word α) n) : Vector α (32 * n) :=
  Vector.ofFn fun i =>
    (v[i.val / 32]'(by omega))[i.val % 32]'(Nat.mod_lt _ (by norm_num))

/-- Carry recurrence for characteristic two.

The generic carrier is intentional: the reference circuit applies this
definition both to `F 2` values and to symbolic `Expression (F 2)` terms.
It is not a full-adder recurrence over fields of other characteristics. -/
def carry {α : Type} [Zero α] [Add α] [Mul α] (x y : Word α) : ℕ → α
  | 0 => 0
  | i + 1 =>
    let c := carry x y i
    (atWord x i + c) * (atWord y i + c) + c

/-- Addition modulo `2^32` for bits in characteristic two.

As with `carry`, the generic signature exists only to share the definition
between concrete GF(2) values and symbolic expressions over GF(2). -/
def addWord {α : Type} [Zero α] [Add α] [Mul α] (x y : Word α) : Word α :=
  Vector.ofFn fun i => atWord x i.val + atWord y i.val + carry x y i.val

def xorWord {α : Type} [Add α] (x y : Word α) : Word α :=
  Vector.ofFn fun i => x[i.val] + y[i.val]

def rotRight {α : Type} (x : Word α) (n : ℕ) : Word α :=
  Vector.ofFn fun i => atWord x (i.val + n)

def stateWord {α : Type} (v : State α) (i : Fin 16) : Word α :=
  Vector.ofFn fun j => v[32 * i.val + j.val]'(by omega)

def setWord {α : Type} (v : State α) (i : Fin 16) (x : Word α) : State α :=
  Vector.ofFn fun j =>
    if h : j.val / 32 = i.val then
      x[j.val % 32]'(Nat.mod_lt _ (by norm_num))
    else
      v[j.val]

def readQuad {α : Type} (v : State α) (a b c d : Fin 16) : Quad α :=
  ⟨stateWord v a, stateWord v b, stateWord v c, stateWord v d⟩

def writeQuad {α : Type} (v : State α) (a b c d : Fin 16) (q : Quad α) : State α :=
  setWord (setWord (setWord (setWord v a q.a) b q.b) c q.c) d q.d

def gFirstValues {α : Type} [Zero α] [Add α] [Mul α]
    (q : Quad α) (mx : Word α) : Quad α :=
  let va := addWord (addWord q.a q.b) mx
  let vd := rotRight (xorWord q.d va) 16
  let vc := addWord q.c vd
  let vb := rotRight (xorWord q.b vc) 12
  ⟨va, vb, vc, vd⟩

def gSecondValues {α : Type} [Zero α] [Add α] [Mul α]
    (q : Quad α) (my : Word α) : Quad α :=
  let va := addWord (addWord q.a q.b) my
  let vd := rotRight (xorWord q.d va) 8
  let vc := addWord q.c vd
  let vb := rotRight (xorWord q.b vc) 7
  ⟨va, vb, vc, vd⟩

def gValues {α : Type} [Zero α] [Add α] [Mul α]
    (q : Quad α) (mx my : Word α) : Quad α :=
  gSecondValues (gFirstValues q mx) my

def g {α : Type} [Zero α] [Add α] [Mul α]
    (v : State α) (a b c d : Fin 16) (mx my : Word α) : State α :=
  writeQuad v a b c d (gValues (readQuad v a b c d) mx my)

def gPairState {α : Type} [Zero α] [Add α] [Mul α]
    (v m : State α)
    (a0 b0 c0 d0 mx0 my0 a1 b1 c1 d1 mx1 my1 : Fin 16) : State α :=
  g (g v a0 b0 c0 d0 (stateWord m mx0) (stateWord m my0))
    a1 b1 c1 d1 (stateWord m mx1) (stateWord m my1)

def roundState {α : Type} [Zero α] [Add α] [Mul α]
    (v m : State α) : State α :=
  let v := gPairState v m 0 4 8 12 0 1 1 5 9 13 2 3
  let v := gPairState v m 2 6 10 14 4 5 3 7 11 15 6 7
  let v := gPairState v m 0 5 10 15 8 9 1 6 11 12 10 11
  gPairState v m 2 7 8 13 12 13 3 4 9 14 14 15

def messagePermutation : Vector (Fin 16) 16 :=
  #v[2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8]

def permute {α : Type} (m : Block α) : Block α :=
  Vector.ofFn fun i => m[(messagePermutation[i.val]).val]'(messagePermutation[i.val]).isLt

def permuteState {α : Type} (m : State α) : State α :=
  flattenWords (permute (splitWords 16 m))

def constWord {α : Type} [Zero α] [One α] (x : ℕ) : Word α :=
  Vector.ofFn fun i => if x.testBit i.val then 1 else 0

def initialState {α : Type} [Zero α] [One α] (w : Vector (Word α) 28) : State α :=
  Vector.ofFn fun i =>
    if hcv : i.val / 32 < 8 then
      atWord (w[i.val / 32]'(by omega)) i.val
    else if hiv : i.val / 32 < 12 then
      atWord (constWord (Specs.Blake3.iv[i.val / 32 - 8]'(by omega))) i.val
    else
      atWord (w[i.val / 32 + 12]'(by omega)) i.val

def initialBlock {α : Type} (w : Vector (Word α) 28) : State α :=
  Vector.ofFn fun i =>
    atWord (w[i.val / 32 + 8]'(by omega)) i.val

structure Config (α : Type) where
  state : State α
  block : State α
deriving ProvableStruct

def stepConfig {α : Type} [Zero α] [Add α] [Mul α] (x : Config α) : Config α :=
  ⟨roundState x.state x.block, permuteState x.block⟩

def steps2 {α : Type} [Zero α] [Add α] [Mul α] (x : Config α) : Config α :=
  stepConfig (stepConfig x)

def steps4 {α : Type} [Zero α] [Add α] [Mul α] (x : Config α) : Config α :=
  steps2 (steps2 x)

def steps7 {α : Type} [Zero α] [Add α] [Mul α] (x : Config α) : Config α :=
  stepConfig (steps2 (steps4 x))

def finalizeState {α : Type} [Add α] (v initial : State α) : State α :=
  Vector.ofFn fun i =>
    if h : i.val < 256 then
      v[i.val] + v[i.val + 256]'(by omega)
    else
      v[i.val] + initial[i.val - 256]'(by omega)

def compressState {α : Type} [Zero α] [One α] [Add α] [Mul α]
    (w : Vector (Word α) 28) : State α :=
  let initial := initialState w
  let result := steps7 ⟨initial, initialBlock w⟩
  finalizeState result.state initial

def compress (input : Vector (F p2) inputBits) : Vector (F p2) outputBits :=
  compressState (splitWords 28 input)

end Blake3Bits

end Interface
end Challenge.Instances.Blake3CompressGF2Canonical
